#included:
#— marauders/SceneDelegate
#
#excluded:
#— Pods
#
#line_length:
#warning: 500 # warning
#error: 750 # error
#
#file_length:
#warning: 500
#error: 750
#
#disabled_rules:
#— colon
#— comma
#— force_cast
#— force_try
#
#opt_in_rules:
#— empty_string
#
#function_body_length:
#warning: 250 # warning
#error: 500 # error
#
#type_body_length:
#warning: 500 # warning
#error: 750 # error
#
#large_tuple:
#warning: 4 # warning
#error: 5 # error
#
#cyclomatic_complexity: 20

disabled_rules:
- trailing_whitespace

opt_in_rules:
- empty_count
- empty_string

excluded:
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 300
    error: 500
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
cyclomatic_complexity:
    warning: 15
    error: 25

reporter: "xcode"
